package bootstrap

import (
	"fmt"
	"strings"
)

// GenerateAgentGuide creates a markdown file for a coding agent to follow.
func GenerateAgentGuide(env *Environment, installDir string) string {
	var sb strings.Builder

	sb.WriteString("# REPOSWARM_INSTALL.md — Agent Instructions\n\n")
	sb.WriteString("You are setting up a local RepoSwarm installation.\n")
	sb.WriteString("Follow each step in order. Verify each step before moving on.\n")
	sb.WriteString("If a step fails, diagnose and fix before continuing.\n\n")

	sb.WriteString("## Environment\n\n")
	sb.WriteString("```\n")
	sb.WriteString(fmt.Sprintf("OS:              %s/%s\n", env.OS, env.Arch))
	sb.WriteString(fmt.Sprintf("Install dir:     %s\n", installDir))
	sb.WriteString(fmt.Sprintf("Docker:          %v (%s)\n", env.HasDocker, env.DockerVer))
	sb.WriteString(fmt.Sprintf("Docker Compose:  %v (%s)\n", env.HasCompose, env.ComposeVer))
	sb.WriteString(fmt.Sprintf("Node.js:         %v (%s)\n", env.HasNode, env.NodeVer))
	sb.WriteString(fmt.Sprintf("Python:          %v (%s)\n", env.HasPython, env.PythonVer))
	sb.WriteString(fmt.Sprintf("Git:             %v (%s)\n", env.HasGit, env.GitVer))
	sb.WriteString(fmt.Sprintf("AWS CLI:         %v\n", env.HasAWSCLI))
	sb.WriteString(fmt.Sprintf("AWS Region:      %s\n", env.AWSRegion))
	sb.WriteString("```\n\n")

	// Missing deps
	missing := env.MissingDeps()
	if len(missing) > 0 {
		sb.WriteString("## Step 0: Install Missing Dependencies\n\n")
		sb.WriteString("These are REQUIRED before proceeding:\n\n")
		for _, dep := range missing {
			sb.WriteString(fmt.Sprintf("- [ ] Install %s\n", dep))
		}
		sb.WriteString("\n")
		sb.WriteString(installInstructions(env, missing))
		sb.WriteString("**Verify all are installed before continuing.**\n\n")
	}

	sb.WriteString("## Step 1: Create Directory Structure\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString(fmt.Sprintf("mkdir -p %s/{temporal,worker,api,ui}\n", installDir))
	sb.WriteString(fmt.Sprintf("cd %s\n", installDir))
	sb.WriteString("```\n\n")

	sb.WriteString("## Step 2: Start Temporal Server\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString(fmt.Sprintf("cd %s/temporal\n", installDir))
	sb.WriteString("```\n\n")
	sb.WriteString("Create `docker-compose.yml`:\n\n")
	sb.WriteString("```yaml\n")
	sb.WriteString(temporalCompose())
	sb.WriteString("```\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("docker compose up -d\n")
	sb.WriteString("```\n\n")
	sb.WriteString("**Verify:** `curl -s http://localhost:7233/api/v1/namespaces | head -c 100`\n")
	sb.WriteString("Expected: JSON response (not connection refused)\n\n")
	sb.WriteString("**Verify:** Open http://localhost:8233 — Temporal UI should load\n\n")

	sb.WriteString("## Step 3: Clone and Start Worker\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString(fmt.Sprintf("cd %s\n", installDir))
	sb.WriteString("git clone https://github.com/royosherove/repo-swarm.git worker\n")
	sb.WriteString("cd worker\n")
	sb.WriteString("python3 -m venv .venv\n")
	sb.WriteString("source .venv/bin/activate\n")
	sb.WriteString("pip install -r requirements.txt\n")
	sb.WriteString("```\n\n")
	sb.WriteString("Create `.env`:\n\n")
	sb.WriteString("```\n")
	sb.WriteString("TEMPORAL_ADDRESS=localhost:7233\n")
	sb.WriteString("TEMPORAL_NAMESPACE=default\n")
	sb.WriteString("TEMPORAL_TASK_QUEUE=investigate-task-queue\n")
	sb.WriteString(fmt.Sprintf("AWS_REGION=%s\n", env.AWSRegion))
	sb.WriteString("DYNAMODB_TABLE=reposwarm-cache\n")
	sb.WriteString("DEFAULT_MODEL=us.anthropic.claude-sonnet-4-6\n")
	sb.WriteString("```\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("python -m worker.main\n")
	sb.WriteString("```\n\n")
	sb.WriteString("**Verify:** Worker logs should show \"Connected to Temporal\" and \"Polling for tasks\"\n")
	sb.WriteString("Run worker in a **separate terminal** or backgrounded.\n\n")

	sb.WriteString("## Step 4: Clone and Start API Server\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString(fmt.Sprintf("cd %s\n", installDir))
	sb.WriteString("git clone https://github.com/loki-bedlam/reposwarm-api.git api\n")
	sb.WriteString("cd api\n")
	sb.WriteString("npm install\n")
	sb.WriteString("```\n\n")
	sb.WriteString("Create `.env`:\n\n")
	sb.WriteString("```\n")
	sb.WriteString("PORT=3000\n")
	sb.WriteString("TEMPORAL_ADDRESS=localhost:7233\n")
	sb.WriteString("TEMPORAL_NAMESPACE=default\n")
	sb.WriteString("TEMPORAL_TASK_QUEUE=investigate-task-queue\n")
	sb.WriteString(fmt.Sprintf("AWS_REGION=%s\n", env.AWSRegion))
	sb.WriteString("DYNAMODB_TABLE=reposwarm-cache\n")
	sb.WriteString("BEARER_TOKEN=local-dev-token-change-me\n")
	sb.WriteString("```\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("npm run build\n")
	sb.WriteString("npm start\n")
	sb.WriteString("```\n\n")
	sb.WriteString("**Verify:** `curl -s http://localhost:3000/v1/health | python3 -m json.tool`\n")
	sb.WriteString("Expected: `{\"status\": \"healthy\", ...}`\n")
	sb.WriteString("Run in a **separate terminal** or backgrounded.\n\n")

	sb.WriteString("## Step 5: Clone and Start UI\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString(fmt.Sprintf("cd %s\n", installDir))
	sb.WriteString("git clone https://github.com/loki-bedlam/reposwarm-ui.git ui\n")
	sb.WriteString("cd ui\n")
	sb.WriteString("npm install\n")
	sb.WriteString("```\n\n")
	sb.WriteString("Create `.env.local`:\n\n")
	sb.WriteString("```\n")
	sb.WriteString("NEXT_PUBLIC_API_URL=http://localhost:3000\n")
	sb.WriteString("```\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("npm run dev\n")
	sb.WriteString("```\n\n")
	sb.WriteString("**Verify:** Open http://localhost:3001 — RepoSwarm UI should load\n\n")

	sb.WriteString("## Step 6: Configure CLI\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("reposwarm config set apiUrl http://localhost:3000/v1\n")
	sb.WriteString("reposwarm config set apiToken local-dev-token-change-me\n")
	sb.WriteString("reposwarm status\n")
	sb.WriteString("```\n\n")
	sb.WriteString("**Verify:** Status shows healthy with Temporal, DynamoDB, and Worker connected.\n\n")

	sb.WriteString("## Step 7: Test End-to-End\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("# Add a public repo\n")
	sb.WriteString("reposwarm repos add is-odd --url https://github.com/jonschlinkert/is-odd --source GitHub\n\n")
	sb.WriteString("# Trigger investigation\n")
	sb.WriteString("reposwarm investigate is-odd\n\n")
	sb.WriteString("# Watch it run\n")
	sb.WriteString("reposwarm watch\n\n")
	sb.WriteString("# When complete, read results\n")
	sb.WriteString("reposwarm results read is-odd\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Done!\n\n")
	sb.WriteString("RepoSwarm is running locally. You have:\n")
	sb.WriteString("- Temporal Server (port 7233, UI at 8233)\n")
	sb.WriteString("- Worker (Python, connected to Temporal)\n")
	sb.WriteString("- API Server (port 3000)\n")
	sb.WriteString("- UI (port 3001)\n")
	sb.WriteString("- CLI configured and ready\n")

	return sb.String()
}
